    version: '3.8'

    volumes:
      datafiles:

    services:
      db:
        image: mysql:5.7.41
        volumes:
          - datafiles:/var/lib/mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: Password123!
          MYSQL_TCP_PORT: 3306

      webapp:
        image: sbredenhof/timesheettest
        depends_on:
          - db
        ports:
          - "8888:80"
        # restart: always
        environment:
          - DBHOST=db
          - DBPORT=3306
          - DBPASSWORD=Password123!
          - DBNAME=bingo-db
          - ASPNETCORE_ENVIRONMENT=Development